### ISSUE TITLE
unable to load resources.

### ISSUE THREAD

**Issue by weedkiller** [PoweredSoft/DynamicQueryAspNetCoreSample#2]
This is simply awesome!
What steps do I need to pull in those packages, from the _Package Manager Console_
It builds fine, but does not load. [BTW check out the castle IT based on the jquery sql builder, he does not have aggregate/sum or count](https://github.com/castle-it/dynamic-linq-query-builder)

![image](https://user-images.githubusercontent.com/21086190/48435590-e1ff4800-e74a-11e8-94ab-32739c689e43.png)

**Comment by dlebee** [comment]
I would do npm i, inside the spa folder, try this and tell me if it works.

**Comment by dlebee** [comment]
> This is simply awesome!
> What steps do I need to pull in those packages, from the _Package Manager Console_
> It builds fine, but does not load. [BTW check out the castle IT based on the jquery sql builder, he does not have aggregate/sum or count](https://github.com/castle-it/dynamic-linq-query-builder)
> 
> ![image](https://user-images.githubusercontent.com/21086190/48435590-e1ff4800-e74a-11e8-94ab-32739c689e43.png)

I would do try the following:
step 1 : npm install -g @angular/cli
step 2 : npm i, inside the spa folder.

If you can do ng build without errors in the spa folder, it should run well after this.

**Comment by dlebee** [comment]
@weedkiller I also updated the read me of the sample.

**Comment by weedkiller** [comment]
Hi @dlebee I updated this, thanks for the pointers, I was able to run it! 

New to angular.. maybe your project is good starting point. It installed, but complainted about some modules called events. I looked around in the pacakage.json file, did not see this. is it needed?

![image](https://user-images.githubusercontent.com/21086190/48500318-94e1ab80-e808-11e8-9ffa-22039ece26e4.png)
____________

I was able to get this far.. can we make path the col names as drop downs, or did you have something else in mind.

![image](https://user-images.githubusercontent.com/21086190/48500599-3963ed80-e809-11e8-8249-f27fb632dafa.png)

**Comment by dlebee** [comment]
@weedkiller 
its the npm world, always has warnings, they should be yellow instead of red, but i guess the output console shows them red, as long as the page displays and you can press go it should work :)

**Comment by weedkiller** [comment]
This is awesome, looks like an XSLT path, perhaps we should use the fluent library to allow the user to build his [].[].[]
> You could do customer.firstName Equals "David" per example.

Can you post a sample path for aggregation. for e.g. I am trying to filter all JohnsSmiths in a table 

1. `(Gamer.Name Contains "JohnSmiths")`, 
2. in capture the flag game more `(Gamer.Mode Equals "Flag21")` , 
3. and sum up his game scores for total, `(Gamer.Score Sum` ??"`)..` (so I can it back to a leaderboard db table)

Two questions: how would I frame the Sum part, to get one row.
What function POSTS the sql to the Server, which function would give me the SQL or Linq statement. So, I can run and insert into the leaderboard table

**Comment by dlebee** [comment]
Sure but this seems to become very specific, and not related to the sample.
If you use gitter.im you could chat with me and we can look into your specific case, and close this issue.

**Comment by weedkiller** [comment]
Doesnt have to be specific, trying to figureout usage, and how can we aggregate.. will join shortly

**Comment by dlebee** [comment]
@weedkiller if you give me a better idea of your table(s) structure i can add it to the drop down and create a button to set all the fields to demonstrate it.

David

**Comment by weedkiller** [comment]
There is a link but I left it out.

```


USE [Tk_DB_v1]
GO

/****** Object:  Table [dbo].[Tickets]    Script Date: 11/15/2018 3:34:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tickets](
	[TicketId] [int] IDENTITY(1,1) NOT NULL,
	[TicketType] [nvarchar](50) NOT NULL,
	[Category] [nvarchar](50) NOT NULL,
	[Title] [nvarchar](500) NOT NULL,
	[Details] [nvarchar](max) NOT NULL,
	[IsHtml] [bit] NOT NULL,
	[TagList] [nvarchar](100) NULL,
	[CreatedBy] [nvarchar](256) NOT NULL,
	[CreatedDate] [datetimeoffset](7) NOT NULL,
	[Owner] [nvarchar](256) NOT NULL,
	[AssignedTo] [nvarchar](256) NULL,
	[TicketStatus] [int] NOT NULL,
	[CurrentStatusDate] [datetimeoffset](7) NOT NULL,
	[CurrentStatusSetBy] [nvarchar](256) NOT NULL,
	[LastUpdateBy] [nvarchar](256) NOT NULL,
	[LastUpdateDate] [datetimeoffset](7) NOT NULL,
	[Priority] [nvarchar](25) NULL,
	[AffectsCustomer] [bit] NOT NULL,
	[Version] [timestamp] NOT NULL,
	[ProjectId] [int] NOT NULL,
	[DueDate] [datetimeoffset](7) NULL,
	[EstimatedDuration] [decimal](18, 2) NULL,
	[ActualDuration] [decimal](18, 2) NULL,
	[TargetDate] [datetimeoffset](7) NULL,
	[ResolutionDate] [datetimeoffset](7) NULL,
	[Type] [int] NULL,
	[ParentId] [int] NULL,
	[PreferredLanguage] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.Tickets] PRIMARY KEY CLUSTERED 
(
	[TicketId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tickets] ADD  DEFAULT (sysdatetimeoffset()) FOR [CreatedDate]
GO

ALTER TABLE [dbo].[Tickets] ADD  DEFAULT ((1)) FOR [ProjectId]
GO

ALTER TABLE [dbo].[Tickets]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Tickets_dbo.Projects_ProjectId] FOREIGN KEY([ProjectId])
REFERENCES [dbo].[Projects] ([ProjectId])
GO

ALTER TABLE [dbo].[Tickets] CHECK CONSTRAINT [FK_dbo.Tickets_dbo.Projects_ProjectId]
GO

/********************************************/


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tasks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[OrderNumber] [int] NOT NULL,
	[AssignedLogId] [int] NULL,
	[IsAssigned] [int] NOT NULL,
	[OTSTaskTypeId] [int] NULL,
	[Comment] [nvarchar](max) NULL,
	[LogComplete] [datetime] NULL,
	[IsLogComplete] [bit] NULL,
	[ActualComplete] [bit] NULL,
	[PlannedStartDate] [datetime] NULL,
	[PlannedCompleteStartDate] [datetime] NULL,
	[IsComplete] [bit] NOT NULL,
	[Unplanned] [bit] NOT NULL,
	[UnplannedCodeId] [int] NULL,
	[UnplannedComments] [nvarchar](max) NULL,
	[IsImport] [bit] NOT NULL,
	[IsArchived] [bit] NULL,
	[OTSProjectCodeId] [int] NULL,
	[BarrierTypeId] [int] NULL,
	[IsBarrier] [bit] NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastModifiedBy] [nvarchar](128) NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO





```

**Comment by dlebee** [comment]
@weedkiller Super I will add it tonight, to the project and try to fake some data, using Bogus.net, if you specify me based on the schema you provided what you'd like to aggregate I can make a button that will preset the criteria how it should be to achieve your needs.

To answer your other question, the query handler will not give you a IQueryable, because if you group data or aggregate data, this involves multiple queries (IQueryable) being materialized.

Hope this answers your other question.

**Comment by dlebee** [comment]
@weedkiller I updated the sample, you may git pull, and look at it.
